### ISSUE TITLE
Feature Request: Add huge pages configuration support to NodeENI resources

### ISSUE THREAD

**Issue by johnlam90** [johnlam90/aws-multi-eni-controller#24]
## Summary

Add cloud-native huge pages configuration support to NodeENI resources, enabling automatic huge pages setup through Kubernetes APIs instead of manual host configuration.

## Motivation

Huge pages are essential for high-performance networking applications, especially when combined with DPDK. Currently, huge pages must be configured manually on worker nodes, which is not cloud-native and doesn't integrate well with the AWS Multi-ENI Controller's automated approach.

### Core Functionality

- **Cloud-Native Configuration**: Configure huge pages (2MB/1GB) through NodeENI custom resources
- **Kubernetes API Integration**: Use native Kubernetes APIs instead of manual host configuration scripts
- **ENI Manager Integration**: Extend the ENI Manager DaemonSet to handle huge pages configuration on worker nodes
- **Multiple Page Sizes**: Support for different huge page sizes (2MB, 1GB) as configurable options
- **Lifecycle Management**: Automatic setup when NodeENI resources are created/updated, proper cleanup on deletion
- **DPDK Integration**: Seamless integration with existing DPDK functionality since huge pages are commonly used with DPDK

### Proposed NodeENI Resource Schema

```yaml
apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: dpdk-with-hugepages
spec:
  nodeSelector:
    ng: high-performance
  subnetIDs:
    - subnet-12345678
  securityGroupIDs:
    - sg-12345678
  deviceIndex: 2
  
  # DPDK Configuration
  enableDPDK: true
  dpdkDriver: "vfio-pci"
  dpdkPCIAddress: "0000:00:07.0"
  dpdkResourceName: "intel.com/sriov_dpdk_1"
  
  # NEW: Huge Pages Configuration
  hugePagesConfig:
    enabled: true
    pageSize: "2Mi"  # Options: "2Mi", "1Gi"
    count: 1024      # Number of huge pages to allocate
    mountPath: "/mnt/huge"  # Optional: custom mount path
    # Alternative configuration for multiple page sizes
    # pages:
    #   - size: "2Mi"
    #     count: 1024
    #   - size: "1Gi" 
    #     count: 4
status:
  hugePagesStatus:
    configured: true
    pageSize: "2Mi"
    allocatedCount: 1024
    availableCount: 1024
    mountPath: "/mnt/huge"
    lastUpdated: "2025-05-28T10:00:00Z"
```

#### 1. Basic Huge Pages with DPDK
```yaml
apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: dpdk-2mb-hugepages
spec:
  nodeSelector:
    workload: dpdk
  subnetIDs:
    - subnet-abc123
  securityGroupIDs:
    - sg-def456
  deviceIndex: 2
  enableDPDK: true
  dpdkPCIAddress: "0000:00:07.0"
  dpdkResourceName: "intel.com/sriov_dpdk"
  hugePagesConfig:
    enabled: true
    pageSize: "2Mi"
    count: 512
```

#### 2. Large Huge Pages (1GB)
```yaml
apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: dpdk-1gb-hugepages
spec:
  nodeSelector:
    instance-type: c5n.18xlarge
  subnetIDs:
    - subnet-xyz789
  securityGroupIDs:
    - sg-ghi012
  deviceIndex: 3
  enableDPDK: true
  dpdkPCIAddress: "0000:00:08.0"
  dpdkResourceName: "intel.com/sriov_dpdk_large"
  hugePagesConfig:
    enabled: true
    pageSize: "1Gi"
    count: 8
```

#### 3. Huge Pages without DPDK (for other high-performance applications)
```yaml
apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: hugepages-only
spec:
  nodeSelector:
    workload: high-memory
  subnetIDs:
    - subnet-mem123
  securityGroupIDs:
    - sg-mem456
  deviceIndex: 2
  hugePagesConfig:
    enabled: true
    pageSize: "2Mi"
    count: 2048
    mountPath: "/dev/hugepages"
```

### 1. NodeENI CRD Updates
- Extend the NodeENI CRD schema to include `hugePagesConfig` field
- Add validation for huge page sizes and counts
- Update status reporting to include huge pages information

### 2. ENI Manager DaemonSet Enhancement
- Add huge pages configuration logic to the ENI Manager
- Implement huge pages allocation/deallocation functions
- Add huge pages status monitoring and reporting
- Ensure proper cleanup when NodeENI resources are deleted

### 3. Integration Points
- **DPDK Integration**: Coordinate huge pages setup with DPDK binding operations
- **Node Resource Management**: Update node resources to reflect huge pages availability
- **Pod Scheduling**: Ensure pods can request and use configured huge pages

### 4. Configuration Management
```go
// Proposed Go structures
type HugePagesConfig struct {
    Enabled   bool   `json:"enabled"`
    PageSize  string `json:"pageSize"`  // "2Mi" or "1Gi"
    Count     int32  `json:"count"`
    MountPath string `json:"mountPath,omitempty"`
}

type HugePagesStatus struct {
    Configured     bool      `json:"configured"`
    PageSize       string    `json:"pageSize"`
    AllocatedCount int32     `json:"allocatedCount"`
    AvailableCount int32     `json:"availableCount"`
    MountPath      string    `json:"mountPath"`
    LastUpdated    metav1.Time `json:"lastUpdated"`
}
```

### Core Functionality
- [ ] NodeENI CRD supports huge pages configuration fields
- [ ] ENI Manager can allocate/deallocate huge pages based on NodeENI specs
- [ ] Support for both 2MB and 1GB huge page sizes
- [ ] Proper status reporting in NodeENI resources
- [ ] Automatic cleanup when NodeENI resources are deleted

### Integration
- [ ] Seamless integration with existing DPDK functionality
- [ ] Huge pages configuration works independently of DPDK (for other use cases)
- [ ] Node resources updated to reflect huge pages availability
- [ ] Compatible with existing SR-IOV device plugin functionality

### Reliability
- [ ] Proper error handling for insufficient memory scenarios
- [ ] Validation of huge page configuration parameters
- [ ] Graceful handling of node reboots and ENI Manager restarts
- [ ] Comprehensive logging for troubleshooting

### Testing
- [ ] Unit tests for huge pages configuration logic
- [ ] Integration tests with DPDK scenarios
- [ ] End-to-end tests with pod scheduling and huge pages consumption
- [ ] Performance tests to verify huge pages effectiveness

### 1. Host System Requirements
- Ensure sufficient memory available for huge pages allocation
- Handle different instance types with varying memory configurations
- Consider NUMA topology for optimal huge pages placement

### 2. Kubernetes Integration
- Update node resources to advertise huge pages availability
- Ensure compatibility with Kubernetes huge pages scheduling
- Handle huge pages resource requests in pod specifications

### 3. AWS-Specific Considerations
- Different EC2 instance types have varying memory configurations
- Consider Nitro system optimizations for huge pages
- Integration with AWS-specific performance features

### 4. Backwards Compatibility
- Ensure existing NodeENI resources continue to work without huge pages configuration
- Graceful handling of nodes that don't support huge pages
- Optional feature that doesn't break existing deployments

## Related Work

- **Current DPDK Implementation**: Build upon existing DPDK functionality in v1.3.5
- **SR-IOV Integration**: Ensure compatibility with current SR-IOV device plugin configuration
- **ENI Manager Architecture**: Leverage the modular ENI Manager architecture introduced in v1.3.4

## Future Enhancements

- **Multi-Size Support**: Support for multiple huge page sizes in a single NodeENI
- **Dynamic Allocation**: Runtime adjustment of huge pages based on workload demands
- **NUMA Awareness**: NUMA-aware huge pages allocation for optimal performance
- **Monitoring Integration**: Metrics and monitoring for huge pages utilization

---

**Baseline Version**: v1.3.5  
**Priority**: Medium  
**Complexity**: Medium-High  
**Dependencies**: None (builds on existing DPDK functionality)
